name = 'alt:V - Zombie Survival'
host = '0.0.0.0'
port = 7788
players = 128
#password = ultra-password
announce = false
#token = YOUR_TOKEN
gamemode = 'Apocalypse'
#website = 'example.com'
language = 'de'
debug = true
description = 'alt:V Apocalypse for alt:V'
modules = [ 'js-module' ]
resources = [
    # All resources and mods should always be loaded before core
    'images',
    'fonts',
    'sounds',
    'rmlui',
    'webview',
    'core'
]